server:
  mode: debug
  httpPort: 8080
  jwtKey: smo3(*kkc
# 数据库配置
db:
  db: mysql
  host: localhost
  port: 33060
  name: myblog
  user: root
  password:
# 七牛云配置
qiniu:
  accessKey: DJnlV6bI1eK1GASiHKfYzr9FRWlVjAg2smwFt8-d
  secretKey: od9SvbBsOqqRiN85UorLNP91CT5zQVTHo0rjlMYw
  bucket: my-gin-blog
  url: http://r9nc6zhlu.hn-bkt.clouddn.com/



